// design/screens/dashboard.jsx
/* global React, Icons, DATA */
const { useMemo: useMemoDash } = React;

function Dashboard({ onNav, onOpenModal }) {
  const today = DATA.today;
  const fmtDate = today.toLocaleDateString('es-ES', { weekday: 'long', day: 'numeric', month: 'long' });
  const upcoming = useMemoDash(() => {
    return [...DATA.events]
      .filter(e => e.day >= today.getDate())
      .sort((a, b) => a.day - b.day || a.start.localeCompare(b.start))
      .slice(0, 5);
  }, []);

  // Mini calendar — 6 weeks
  const miniCal = useMemoDash(() => {
    const first = new Date(2026, 4, 1); // 1 may 2026
    const startDow = (first.getDay() + 6) % 7; // L=0
    const cells = [];
    for (let i = 0; i < 42; i++) {
      const d = i - startDow + 1;
      cells.push(d >= 1 && d <= 31 ? d : null);
    }
    return cells;
  }, []);

  const eventsByDay = useMemoDash(() => {
    const m = {};
    DATA.events.forEach(e => { (m[e.day] ||= []).push(e); });
    return m;
  }, []);

  return (
    <div className="page">
      {/* greeting */}
      <div className="page-header">
        <div>
          <div className="uppercase-tag">{fmtDate}</div>
          <h1 className="page-title mt-1">Buenos días, Daniel.</h1>
          <div className="page-subtitle">3 eventos hoy · 7 tareas en progreso · racha de meditación de 22 días</div>
        </div>
        <div className="flex gap-2">
          <button className="btn" onClick={() => onOpenModal('event')}><Icons.Plus size={13} /> Evento</button>
          <button className="btn btn-primary" onClick={() => onOpenModal('todo')}><Icons.Plus size={13} /> Nueva tarea</button>
        </div>
      </div>

      {/* Stat row */}
      <div className="grid" style={{ gridTemplateColumns: 'repeat(4, 1fr)', gap: 14, marginBottom: 22 }}>
        <StatCard label="Balance · mayo" value="+1.665€" sub="vs. abr +312€" tone="success" icon={Icons.TrendUp} />
        <StatCard label="Tareas hoy" value="3" sub="2 ALTA · 1 MEDIA" tone="primary" icon={Icons.Kanban} />
        <StatCard label="Eventos esta semana" value="6" sub="próximo: standup L 09:30" tone="default" icon={Icons.Calendar} />
        <StatCard label="Racha más larga" value="22d" sub="Meditar 10 min" tone="accent" icon={Icons.Flame} />
      </div>

      {/* Two-column main */}
      <div className="grid" style={{ gridTemplateColumns: '1.4fr 1fr', gap: 18 }}>
        {/* Left col */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
          {/* Upcoming events */}
          <div className="panel">
            <div className="panel-header">
              <div>
                <div className="panel-title">Próximos eventos</div>
                <div className="panel-sub">Hoy → mañana → resto de la semana</div>
              </div>
              <button className="btn btn-sm btn-ghost" onClick={() => onNav('calendar')}>Abrir calendario →</button>
            </div>
            <div>
              {upcoming.map(e => (
                <div key={e.id} style={{
                  display: 'grid', gridTemplateColumns: '60px 4px 1fr auto',
                  alignItems: 'center', gap: 14,
                  padding: '12px 18px',
                  borderTop: '1px solid var(--color-border-soft)',
                }}>
                  <div>
                    <div className="mono text-xs text-faint">{['may'][0]} {String(e.day).padStart(2,'0')}</div>
                    <div className="mono text-sm">{e.start}</div>
                  </div>
                  <div style={{ width: 3, height: 30, background: e.color, borderRadius: 3 }} />
                  <div>
                    <div style={{ fontSize: 13, fontWeight: 500 }}>{e.title}</div>
                    <div className="text-xs text-muted mono">{e.cat} · {e.start}–{e.end} {e.notify ? '· 🔔 ' + e.notify + ' min antes' : ''}</div>
                  </div>
                  <button className="btn btn-ghost btn-icon"><Icons.Dots size={14} /></button>
                </div>
              ))}
            </div>
          </div>

          {/* In progress */}
          <div className="panel">
            <div className="panel-header">
              <div>
                <div className="panel-title">En progreso · Proyecto OmniDesk</div>
                <div className="panel-sub">3 tareas activas, 2 en revisión</div>
              </div>
              <button className="btn btn-sm btn-ghost" onClick={() => onNav('todos')}>Ver tablero →</button>
            </div>
            <div style={{ padding: '6px 0 12px' }}>
              {DATA.todos.items.filter(t => t.col === 'col-progress' || t.col === 'col-review').map(t => (
                <div key={t.id} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '8px 18px' }}>
                  <span style={{
                    width: 8, height: 8, borderRadius: 2,
                    background: t.priority === 'ALTA' ? 'var(--color-danger)' : t.priority === 'MEDIA' ? 'var(--color-accent)' : 'var(--color-text-faint)'
                  }} />
                  <span style={{ flex: 1, fontSize: 13 }}>{t.title}</span>
                  <span className="chip" style={{ fontSize: 10 }}>{t.col === 'col-progress' ? 'PROGRESO' : 'REVISIÓN'}</span>
                  <span className="mono text-xs text-faint" style={{ minWidth: 50, textAlign: 'right' }}>{t.due}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Finance snapshot */}
          <div className="panel">
            <div className="panel-header">
              <div>
                <div className="panel-title">Wishlist · botes de ahorro</div>
                <div className="panel-sub">3 botes activos · 2.610€ ahorrados</div>
              </div>
              <button className="btn btn-sm btn-ghost" onClick={() => onNav('finance')}>Ver wishlist →</button>
            </div>
            <div className="panel-pad">
              {DATA.savingPots.slice(0, 3).map(pot => {
                const pct = (pot.saved / pot.goal) * 100;
                return (
                  <div key={pot.id} style={{ marginBottom: 12 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 5 }}>
                      <span style={{ fontSize: 16 }}>{pot.icon}</span>
                      <span style={{ flex: 1, fontSize: 13, fontWeight: 500 }}>{pot.name}</span>
                      <span className="mono text-xs" style={{ color: pot.color, fontWeight: 600 }}>{Math.round(pct)}%</span>
                    </div>
                    <div style={{ height: 5, background: 'var(--color-surface-2)', borderRadius: 3, overflow: 'hidden' }}>
                      <div style={{ width: pct + '%', height: '100%', background: pot.color }}/>
                    </div>
                    <div className="mono text-xs text-faint mt-1">
                      <strong style={{ color: 'var(--color-text-muted)' }}>{pot.saved.toLocaleString('es-ES')}€</strong> / {pot.goal.toLocaleString('es-ES')}€ · {Math.ceil((pot.goal - pot.saved) / pot.monthly)} meses
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Right col */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
          {/* Mini calendar */}
          <div className="panel">
            <div className="panel-header">
              <div className="panel-title">Mayo 2026</div>
              <div className="flex gap-1">
                <button className="btn btn-ghost btn-icon"><Icons.Chevron size={12} style={{ transform: 'rotate(180deg)' }} /></button>
                <button className="btn btn-ghost btn-icon"><Icons.Chevron size={12} /></button>
              </div>
            </div>
            <div className="panel-pad">
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 2, marginBottom: 6 }}>
                {['L','M','X','J','V','S','D'].map(d => (
                  <div key={d} className="mono text-xs text-faint" style={{ textAlign: 'center', padding: 4 }}>{d}</div>
                ))}
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, 1fr)', gap: 2 }}>
                {miniCal.map((d, i) => {
                  const isToday = d === 16;
                  const has = d && eventsByDay[d];
                  return (
                    <div key={i} style={{
                      aspectRatio: '1',
                      borderRadius: 4,
                      display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
                      fontSize: 12,
                      background: isToday ? 'var(--color-primary)' : 'transparent',
                      color: isToday ? '#fff' : d ? 'var(--color-text)' : 'transparent',
                      fontWeight: isToday ? 600 : 400,
                      position: 'relative',
                      cursor: d ? 'pointer' : 'default',
                    }}>
                      {d || '·'}
                      {has && !isToday && (
                        <div style={{
                          position: 'absolute', bottom: 3, display: 'flex', gap: 1,
                        }}>
                          {has.slice(0, 3).map((e, j) => (
                            <div key={j} style={{ width: 4, height: 4, borderRadius: 50, background: e.color }} />
                          ))}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

          {/* Habits today */}
          <div className="panel">
            <div className="panel-header">
              <div>
                <div className="panel-title">Hábitos · hoy</div>
                <div className="panel-sub">Sábado 16 mayo</div>
              </div>
              <button className="btn btn-sm btn-ghost" onClick={() => onNav('habits')}>Ver todos →</button>
            </div>
            <div style={{ padding: '4px 14px 14px' }}>
              {DATA.habits.slice(0, 5).map(h => (
                <div key={h.id} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '8px 4px' }}>
                  <div style={{
                    width: 22, height: 22, borderRadius: 6,
                    background: h.week[6] ? 'var(--color-success)' : 'transparent',
                    border: '1px solid ' + (h.week[6] ? 'transparent' : 'var(--color-border)'),
                    display: 'grid', placeItems: 'center',
                  }}>
                    {h.week[6] === 1 && <Icons.Check size={12} stroke="#fff" />}
                  </div>
                  <span style={{ flex: 1, fontSize: 13 }}>{h.emoji} {h.name}</span>
                  <span className="mono text-xs text-muted">{h.streak}d</span>
                </div>
              ))}
            </div>
          </div>

          {/* Recent notes */}
          <div className="panel">
            <div className="panel-header">
              <div>
                <div className="panel-title">Notas recientes</div>
                <div className="panel-sub">Última actividad</div>
              </div>
              <button className="btn btn-sm btn-ghost" onClick={() => onNav('notes')}>Ver todas →</button>
            </div>
            <div style={{ padding: '4px 14px 14px' }}>
              {DATA.notes.slice(0, 4).map(n => (
                <div key={n.id} style={{ display: 'flex', alignItems: 'flex-start', gap: 10, padding: '8px 4px', cursor: 'pointer' }} onClick={() => onNav('notes')}>
                  <span style={{ fontSize: 16 }}>{n.icon}</span>
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <div style={{ fontSize: 13, fontWeight: 500 }}>{n.title}</div>
                    <div className="text-xs text-muted mono">{n.updated}</div>
                  </div>
                  {n.pinned && <Icons.Pin size={12} stroke="var(--color-accent)" />}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function StatCard({ label, value, sub, tone, icon: I }) {
  const colorMap = {
    primary: 'var(--color-primary)',
    success: 'var(--color-success)',
    accent: 'var(--color-accent)',
    default: 'var(--color-text-muted)',
  };
  return (
    <div className="panel panel-pad" style={{ position: 'relative', overflow: 'hidden' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div className="uppercase-tag">{label}</div>
        <I size={14} stroke={colorMap[tone]} />
      </div>
      <div className="mono" style={{ fontSize: 26, fontWeight: 600, marginTop: 6, letterSpacing: '-0.02em' }}>{value}</div>
      <div className="text-xs text-muted mono mt-1">{sub}</div>
    </div>
  );
}

window.Dashboard = Dashboard;

// frontend/src/app/features/dashboard/dashboard.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, OnInit, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DatePipe } from '@angular/common';

import { AuthService } from '../../core/services/auth.service';
import { DashboardService } from './dashboard.service';
import type { DashboardData } from './dashboard.types';

interface MiniCell {
  day: number | null;
  isToday: boolean;
  dots: string[];
}

@Component({
  selector: 'app-dashboard',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, DatePipe],
  template: `
    <div class="page">
      @if (data(); as d) {
        <!-- Greeting -->
        <header class="page-header">
          <div>
            <div class="uppercase-tag">{{ today() }}</div>
            <h1 class="page-title mt-1">{{ greeting() }}</h1>
            <p class="page-subtitle">{{ subtitle(d) }}</p>
          </div>
          <div class="flex gap-2 shrink-0">
            <a routerLink="/app/calendar" class="btn btn-sm">📅 Calendar</a>
            <a routerLink="/app/todos" class="btn btn-sm btn-primary">✓ Tasks</a>
          </div>
        </header>

        <!-- Stat row -->
        <div class="stat-row">
          <div class="stat-card">
            <div class="stat-top">
              <span class="uppercase-tag">Balance · {{ monthLabel() }}</span>
              <span>{{ d.stats.balance >= 0 ? '📈' : '📉' }}</span>
            </div>
            <div
              class="stat-value mono"
              [class.text-success]="d.stats.balance >= 0"
              [class.text-danger]="d.stats.balance < 0"
            >
              {{ formatCurrency(d.stats.balance, d.stats.currency) }}
            </div>
            <div class="stat-sub mono">
              @if (d.stats.balanceDelta !== null) {
                {{ formatDelta(d.stats.balanceDelta, d.stats.currency) }} vs last month
              } @else {
                this month
              }
            </div>
          </div>

          <div class="stat-card">
            <div class="stat-top">
              <span class="uppercase-tag">Tasks today</span>
              <span>🗂️</span>
            </div>
            <div class="stat-value mono text-primary">{{ d.stats.todoToday }}</div>
            <div class="stat-sub mono">
              {{ d.stats.todoHigh }} high priority
            </div>
          </div>

          <div class="stat-card">
            <div class="stat-top">
              <span class="uppercase-tag">Events this week</span>
              <span>📅</span>
            </div>
            <div class="stat-value mono">{{ d.stats.eventsThisWeek }}</div>
            <div class="stat-sub mono truncate">
              {{ d.stats.nextEventLabel ?? 'nothing scheduled' }}
            </div>
          </div>

          <div class="stat-card">
            <div class="stat-top">
              <span class="uppercase-tag">Best streak</span>
              <span>🔥</span>
            </div>
            <div class="stat-value mono" style="color: var(--color-accent)">{{ d.stats.bestStreak }}d</div>
            <div class="stat-sub mono truncate">
              {{ d.stats.bestStreakHabit ?? 'no habits yet' }}
            </div>
          </div>
        </div>

        <!-- Two-column main -->
        <div class="main-grid">
          <!-- Left column -->
          <div class="col">
            <!-- Upcoming events -->
            <section class="panel">
              <div class="panel-header">
                <div>
                  <div class="panel-title">Upcoming events</div>
                  <div class="panel-sub">Today → this week</div>
                </div>
                <a routerLink="/app/calendar" class="btn btn-sm btn-ghost">Open calendar →</a>
              </div>
              @if (d.upcomingEvents.length === 0) {
                <p class="empty">No upcoming events</p>
              } @else {
                @for (e of d.upcomingEvents; track e.id) {
                  <a routerLink="/app/calendar" class="event-row panel-row">
                    <div class="event-when">
                      <div class="mono text-xs text-faint">{{ e.startDate | date: 'MMM dd' }}</div>
                      <div class="mono text-sm">{{ e.allDay ? 'all day' : (e.startDate | date: 'HH:mm') }}</div>
                    </div>
                    <div class="event-bar" [style.background]="e.color"></div>
                    <div class="min-w-0">
                      <div class="event-title">{{ e.title }}</div>
                      <div class="text-xs text-muted mono truncate">
                        {{ e.startDate | date: 'EEE' }}@if (e.location) { · 📍 {{ e.location }} }
                      </div>
                    </div>
                  </a>
                }
              }
            </section>

            <!-- Tasks in progress -->
            <section class="panel">
              <div class="panel-header">
                <div>
                  <div class="panel-title">On your plate</div>
                  <div class="panel-sub">{{ d.todosInProgress.length }} task(s) today</div>
                </div>
                <a routerLink="/app/todos" class="btn btn-sm btn-ghost">View board →</a>
              </div>
              @if (d.todosInProgress.length === 0) {
                <p class="empty">Nothing for today. Enjoy your day.</p>
              } @else {
                <div class="list-pad">
                  @for (t of d.todosInProgress; track t.id) {
                    <div class="todo-row">
                      <span
                        class="prio-dot"
                        [style.background]="prioColor(t.priority)"
                      ></span>
                      <span class="flex-1 text-sm truncate">{{ t.title }}</span>
                      <span class="chip">{{ t.column.name }}</span>
                      @if (t.dueDate) {
                        <span class="mono text-xs text-faint shrink-0">{{ t.dueDate | date: 'HH:mm' }}</span>
                      }
                    </div>
                  }
                </div>
              }
            </section>

            <!-- Savings pots -->
            @if (d.savingsPots.length > 0) {
              <section class="panel">
                <div class="panel-header">
                  <div>
                    <div class="panel-title">Savings pots</div>
                    <div class="panel-sub">Your active goals</div>
                  </div>
                  <a routerLink="/app/finance/organizer" class="btn btn-sm btn-ghost">View goals →</a>
                </div>
                <div class="panel-pad">
                  @for (p of d.savingsPots; track p.id) {
                    <div class="pot">
                      <div class="pot-head">
                        <span>{{ p.icon ?? '🎯' }}</span>
                        <span class="flex-1 text-sm font-medium truncate">{{ p.name }}</span>
                        <span class="mono text-xs font-semibold" [style.color]="p.color">{{ p.percent }}%</span>
                      </div>
                      <div class="bar">
                        <div class="bar-fill" [style.width.%]="p.percent" [style.background]="p.color"></div>
                      </div>
                      <div class="mono text-xs text-faint mt-1">
                        <strong class="text-muted">{{ formatCurrency(p.saved, d.stats.currency) }}</strong>
                        / {{ formatCurrency(p.goal, d.stats.currency) }}
                      </div>
                    </div>
                  }
                </div>
              </section>
            }
          </div>

          <!-- Right column -->
          <div class="col">
            <!-- Mini calendar -->
            <section class="panel">
              <div class="panel-header">
                <div class="panel-title">{{ monthLabel() }} {{ year() }}</div>
              </div>
              <div class="panel-pad">
                <div class="cal-grid cal-dow">
                  @for (dl of dowLabels; track $index) {
                    <div class="mono text-xs text-faint cal-dow-cell">{{ dl }}</div>
                  }
                </div>
                <div class="cal-grid">
                  @for (c of miniCells(); track $index) {
                    <div class="cal-cell" [class.cal-today]="c.isToday" [class.cal-empty]="!c.day">
                      {{ c.day ?? '' }}
                      @if (c.dots.length && !c.isToday) {
                        <div class="cal-dots">
                          @for (col of c.dots; track $index) {
                            <span class="cal-dot" [style.background]="col"></span>
                          }
                        </div>
                      }
                    </div>
                  }
                </div>
              </div>
            </section>

            <!-- Habits today -->
            <section class="panel">
              <div class="panel-header">
                <div>
                  <div class="panel-title">Habits · today</div>
                  <div class="panel-sub">{{ habitsDone(d) }}/{{ d.habitsToday.length }} done</div>
                </div>
                <a routerLink="/app/habits" class="btn btn-sm btn-ghost">View all →</a>
              </div>
              @if (d.habitsToday.length === 0) {
                <p class="empty">No habits yet</p>
              } @else {
                <div class="list-pad">
                  @for (h of d.habitsToday; track h.id) {
                    <div class="habit-row">
                      <span class="habit-check" [class.done]="h.doneToday">
                        @if (h.doneToday) { ✓ }
                      </span>
                      <span class="flex-1 text-sm truncate">{{ h.icon ?? '🔁' }} {{ h.name }}</span>
                      <span class="mono text-xs text-muted shrink-0">{{ h.streak }}d</span>
                    </div>
                  }
                </div>
              }
            </section>

            <!-- Recent notes -->
            <section class="panel">
              <div class="panel-header">
                <div>
                  <div class="panel-title">Recent notes</div>
                  <div class="panel-sub">Latest activity</div>
                </div>
                <a routerLink="/app/notes" class="btn btn-sm btn-ghost">View all →</a>
              </div>
              @if (d.recentNotes.length === 0) {
                <p class="empty">No notes yet</p>
              } @else {
                <div class="list-pad">
                  @for (n of d.recentNotes; track n.id) {
                    <a
                      routerLink="/app/notes"
                      [queryParams]="{ note: n.id }"
                      class="note-row"
                    >
                      <span>{{ n.icon ?? '📝' }}</span>
                      <div class="min-w-0 flex-1">
                        <div class="text-sm font-medium truncate">{{ n.title || 'Untitled' }}</div>
                        <div class="text-xs text-muted mono">{{ n.updatedAt | date: 'd MMM, HH:mm' }}</div>
                      </div>
                    </a>
                  }
                </div>
              }
            </section>
          </div>
        </div>
      } @else if (loading()) {
        <p class="text-text-muted p-6">Loading…</p>
      } @else if (error()) {
        <p class="text-danger p-6">{{ error() }}</p>
      }
    </div>
  `,
  styles: [`
    .page { padding: 28px 32px 80px; max-width: 1400px; margin: 0 auto; }
    @media (max-width: 640px) { .page { padding: 18px 16px 64px; } }

    .page-header {
      display: flex; align-items: flex-end; justify-content: space-between;
      gap: 16px; margin-bottom: 24px; flex-wrap: wrap;
    }
    .page-title { font-size: 26px; font-weight: 600; letter-spacing: -0.02em; line-height: 1.1; }
    .page-subtitle { color: var(--color-text-muted); font-size: 13px; margin-top: 4px; }

    .stat-row {
      display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; margin-bottom: 22px;
    }
    .stat-top { display: flex; justify-content: space-between; align-items: flex-start; font-size: 14px; }
    .stat-value { font-size: 26px; font-weight: 600; margin-top: 6px; letter-spacing: -0.02em; }
    .stat-sub { font-size: 11px; color: var(--color-text-muted); margin-top: 4px; }

    .main-grid { display: grid; grid-template-columns: 1.4fr 1fr; gap: 18px; }
    .col { display: flex; flex-direction: column; gap: 18px; }

    @media (max-width: 900px) {
      .stat-row { grid-template-columns: repeat(2, 1fr); }
      .main-grid { grid-template-columns: 1fr; }
    }
    @media (max-width: 420px) {
      .stat-row { grid-template-columns: 1fr; }
    }

    .empty { font-size: 13px; color: var(--color-text-muted); font-style: italic; padding: 16px 18px; }
    .list-pad { padding: 6px 8px 10px; }

    .text-muted { color: var(--color-text-muted); }
    .text-faint { color: var(--color-text-faint); }
    .text-success { color: var(--color-success); }
    .text-danger { color: var(--color-danger); }
    .text-primary { color: var(--color-primary); }

    /* Events */
    .event-row {
      display: grid; grid-template-columns: 56px 3px 1fr; align-items: center; gap: 14px;
      padding: 11px 18px; color: inherit; text-decoration: none;
      transition: background 100ms;
    }
    .event-row:hover { background: var(--color-surface-hover); }
    .event-when { text-align: left; }
    .event-bar { width: 3px; height: 30px; border-radius: 3px; }
    .event-title { font-size: 13px; font-weight: 500; }

    /* Todos */
    .todo-row { display: flex; align-items: center; gap: 10px; padding: 7px 10px; }
    .prio-dot { width: 8px; height: 8px; border-radius: 2px; flex-shrink: 0; }

    /* Savings */
    .pot { margin-bottom: 14px; }
    .pot:last-child { margin-bottom: 0; }
    .pot-head { display: flex; align-items: center; gap: 10px; margin-bottom: 5px; }
    .bar { height: 5px; background: var(--color-surface-2); border-radius: 3px; overflow: hidden; }
    .bar-fill { height: 100%; border-radius: 3px; transition: width 0.3s; }

    /* Mini calendar */
    .cal-grid { display: grid; grid-template-columns: repeat(7, 1fr); gap: 2px; }
    .cal-dow { margin-bottom: 6px; }
    .cal-dow-cell { text-align: center; padding: 4px 0; }
    .cal-cell {
      aspect-ratio: 1; border-radius: 4px;
      display: flex; flex-direction: column; align-items: center; justify-content: center;
      font-size: 12px; position: relative; color: var(--color-text);
    }
    .cal-empty { color: transparent; }
    .cal-today { background: var(--color-primary); color: #fff; font-weight: 600; }
    .cal-dots { position: absolute; bottom: 3px; display: flex; gap: 1px; }
    .cal-dot { width: 4px; height: 4px; border-radius: 50%; }

    /* Habits */
    .habit-row { display: flex; align-items: center; gap: 12px; padding: 7px 6px; }
    .habit-check {
      width: 22px; height: 22px; border-radius: 6px; flex-shrink: 0;
      border: 1px solid var(--color-border);
      display: grid; place-items: center; font-size: 12px; color: #fff;
    }
    .habit-check.done { background: var(--color-success); border-color: transparent; }

    /* Notes */
    .note-row {
      display: flex; align-items: flex-start; gap: 10px; padding: 7px 6px;
      color: inherit; text-decoration: none; border-radius: var(--radius-sm);
      transition: background 100ms;
    }
    .note-row:hover { background: var(--color-surface-hover); }

    .mt-1 { margin-top: 4px; }
    .font-medium { font-weight: 500; }
    .font-semibold { font-weight: 600; }
    .text-xs { font-size: 11px; }
    .text-sm { font-size: 13px; }
    .flex { display: flex; }
    .flex-1 { flex: 1; }
    .gap-2 { gap: 8px; }
    .shrink-0 { flex-shrink: 0; }
    .min-w-0 { min-width: 0; }
    .truncate { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  `],
})
export class DashboardComponent implements OnInit {
  private readonly auth = inject(AuthService);
  private readonly dashboard = inject(DashboardService);

  protected readonly data = signal<DashboardData | null>(null);
  protected readonly loading = signal(true);
  protected readonly error = signal<string | null>(null);

  protected readonly dowLabels = ['M', 'T', 'W', 'T', 'F', 'S', 'S'];

  protected readonly greeting = computed(() => {
    const u = this.auth.user();
    const name = u?.displayName ?? u?.email?.split('@')[0] ?? null;
    const h = new Date().getHours();
    const part = h < 12 ? 'Good morning' : h < 19 ? 'Good afternoon' : 'Good evening';
    return name ? `${part}, ${name}.` : `${part}.`;
  });

  protected readonly today = computed(() =>
    new Date().toLocaleDateString('en-US', { weekday: 'long', day: 'numeric', month: 'long' }),
  );

  protected readonly monthLabel = computed(() =>
    new Date().toLocaleDateString('en-US', { month: 'long' }),
  );

  protected readonly year = computed(() => new Date().getFullYear());

  protected readonly miniCells = computed<MiniCell[]>(() => {
    const d = this.data();
    const now = new Date();
    const year = now.getFullYear();
    const month = now.getMonth();
    const first = new Date(year, month, 1);
    const startDow = (first.getDay() + 6) % 7; // Monday-first
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    const todayDate = now.getDate();

    const dotsByDay = new Map<number, string[]>();
    for (const e of d?.monthEvents ?? []) {
      const arr = dotsByDay.get(e.day) ?? [];
      if (arr.length < 3) arr.push(e.color);
      dotsByDay.set(e.day, arr);
    }

    const cells: MiniCell[] = [];
    for (let i = 0; i < 42; i++) {
      const day = i - startDow + 1;
      const valid = day >= 1 && day <= daysInMonth;
      cells.push({
        day: valid ? day : null,
        isToday: valid && day === todayDate,
        dots: valid ? dotsByDay.get(day) ?? [] : [],
      });
    }
    return cells;
  });

  ngOnInit(): void {
    this.dashboard.load().subscribe({
      next: (d) => {
        this.data.set(d);
        this.loading.set(false);
      },
      error: () => {
        this.loading.set(false);
        this.error.set('Could not load the dashboard');
      },
    });
  }

  protected subtitle(d: DashboardData): string {
    const parts: string[] = [];
    parts.push(`${d.stats.eventsThisWeek} event(s) this week`);
    parts.push(`${d.stats.todoToday} task(s) today`);
    if (d.stats.bestStreak > 0 && d.stats.bestStreakHabit) {
      parts.push(`${d.stats.bestStreak}-day ${d.stats.bestStreakHabit} streak`);
    }
    return parts.join(' · ');
  }

  protected habitsDone(d: DashboardData): number {
    return d.habitsToday.filter((h) => h.doneToday).length;
  }

  protected prioColor(p: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT'): string {
    if (p === 'HIGH' || p === 'URGENT') return 'var(--color-danger)';
    if (p === 'MEDIUM') return 'var(--color-accent)';
    return 'var(--color-text-faint)';
  }

  protected formatCurrency(value: number, currency: string): string {
    try {
      return new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency,
        maximumFractionDigits: 0,
      }).format(value);
    } catch {
      return `${currency} ${value.toFixed(0)}`;
    }
  }

  protected formatDelta(value: number, currency: string): string {
    return (value >= 0 ? '+' : '') + this.formatCurrency(value, currency);
  }
}
